### ISSUE TITLE
Druid log on Druid unified web console

### ISSUE THREAD

**Issue by arvindsaket** [spaghettifunk/terraform-aws-druid#17]
**Is your feature request related to a problem? Please describe.**
IS there any way to see the Druids logs on the Druid unified web console?
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Please provide the steps to configure the druid to get the logs on the Druid unified web console.

**Comment by spaghettifunk** [comment]
Hi @arvindsaket! Thanks for opening an issue 😄 Although, I think this is something that you should address to the Apache Druid Google group. I believe that's a feature that is not currently available in Druid AFAIK. I don't think it's possible to see the logs in the Druid web console but you can see them in the Pods in your Kubernetes cluster. My advice is to redirect your logs to Elasticsearch and visualise them from there. I hope that helps.

I'm going to close this issue since is not related to the terraform module itself.

**Comment by arvindsaket** [comment]
Thanks a lot @spaghettifunk for the reply. Will setup humio to see the
Druid pods logs.
Also thanks a lot for writing such a great terraform module for the Druid.
It is very help for Druid learners like me.
----
Regards,
Arvind Singh
Cell: +1-650-603-1484
